CREATE PROCEDURE deleteSermonBlogEntry
@id smallint
AS
DELETE FROM ITEM_ENCLOSURE WHERE ITEM_ID = @id
DELETE FROM ITEM_DESCRIPTION WHERE ITEM_ID = @id
DELETE FROM SERMON_TEXT_REFERENCE WHERE ITEM_ID = @id
DELETE FROM item WHERE ITEM_ID = @id