CREATE PROCEDURE deleteSermonBlogComment
@item_id smallint
AS
DELETE FROM ITEM_DESCRIPTION WHERE ITEM_ID = @item_id;
DELETE FROM ITEM_COMMENT WHERE COMMENT_ID = @item_id;
DELETE FROM ITEM_DESCRIPTION WHERE ITEM_ID = @item_id;