
CREATE  PROCEDURE findAllActiveRecommendedReadings
@channelId tinyint
AS
SELECT
	ITEM.ITEM_ID,
	TITLE,
	LINK,
	AUTHOR,
	URL
FROM
	ITEM
	LEFT OUTER JOIN
		ITEM_ENCLOSURE
		ON
			ITEM.ITEM_ID = ITEM_ENCLOSURE.ITEM_ID
WHERE
	CHANNEL_ID = @channelId
	AND ACTIVE = 1
ORDER BY
	LAST_UPD_TMS ASC