<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    Title="Event Calendar Maintenance Page" ValidateRequest="false" %>
<script type="text/C#" runat="server">
    public void Updating(Object source, SqlDataSourceCommandEventArgs eventArgs)
    {
        eventArgs.Command.Parameters["@channelId"].Value = ((DropDownList)FormView1.FindControl("ChannelDropDownBox")).SelectedValue;
    }
</script>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:SqlDataSource ID="CalendarSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:RPC %>"
        SelectCommand="findEventsFuture" SelectCommandType="StoredProcedure"
        DeleteCommand="deleteEvent" DeleteCommandType="StoredProcedure"
        UpdateCommand="updateEvent" UpdateCommandType="StoredProcedure"
        InsertCommand="createEvent" InsertCommandType="StoredProcedure">
        <SelectParameters>
            <asp:Parameter Name="channelIdSpecial" DefaultValue="3" />
            <asp:Parameter Name="channelIdRegular" DefaultValue="8" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="item_id" />
            <asp:Parameter Name="title" />
            <asp:Parameter Name="pubDate" Type="DateTime" />
            <asp:Parameter Name="channelId" />
            <asp:Parameter Name="description" />
            <asp:Parameter Name="allDayEvent" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="channelId" DefaultValue="3" />
            <asp:Parameter Name="title" />
            <asp:Parameter Name="pubDate" Type="DateTime" />
            <asp:Parameter Name="description" />
            <asp:Parameter Name="allDayEvent" />
        </InsertParameters>
    </asp:SqlDataSource> 
    <table>
        <asp:DetailsView ID="FormView1" DataSourceID="CalendarSqlDataSource" runat="server"
            AutoGenerateRows="False" AutoGenerateInsertButton="True" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" DataKeyNames="item_id" AllowPaging="True" PagerSettings-Mode="NumericFirstLast">
            <PagerSettings Mode="NumericFirstLast"></PagerSettings>
            <Fields>
                <asp:BoundField DataField="item_id" HeaderText="ID" SortExpression="item_id" Visible="false" />
                <asp:BoundField DataField="pubDate" HeaderText="Date" SortExpression="pubDate" />
                <asp:BoundField DataField="title" HeaderText="Title" SortExpression="title" />
                <asp:TemplateField HeaderText="Description" SortExpression="description">
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("description") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Columns="50" Rows="10" Text='<%# Bind("description") %>'
                            TextMode="MultiLine"></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Columns="50" Rows="10" Text='<%# Bind("description") %>'
                            TextMode="MultiLine"></asp:TextBox>
                    </InsertItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Event Type">
                    <ItemTemplate>
                        <asp:Label runat="server"><%# (Byte)Eval("channelId") == 3 ? "Special Event" : "Regular Event" %></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList SelectedValue='<%# Bind("channelId") %>' id="ChannelDropDownBox" runat="server">
                            <asp:ListItem Value="8">Regular Event</asp:ListItem>
                            <asp:ListItem Value="3">Special Event</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:DropDownList SelectedValue='<%# Bind("channelId") %>' id="ChannelDropDownBox" runat="server">
                            <asp:ListItem Value="8">Regular Event</asp:ListItem>
                            <asp:ListItem Value="3">Special Event</asp:ListItem>
                        </asp:DropDownList>
                    </InsertItemTemplate>
                </asp:TemplateField>
                <asp:CheckBoxField DataField="allDayEvent" HeaderText="All Day Event" />
            </Fields>
        </asp:DetailsView>
    </table>
    <div style="height: 20em">
    </div>
</asp:Content>
