<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" Title="Reformed Presbyterian Church" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
<h4>Church Resources</h4>
      <asp:Menu id="SiteTreeView" 
        DataSourceID="SiteMapSource"
        AutoGenerateDataBindings="True"
        runat="server">
      </asp:Menu>

      <asp:SiteMapDataSource ID="SiteMapSource" runat="server" StartingNodeUrl="~/resources.aspx" ShowStartingNode="false" />
</asp:Content>

