CREATE PROCEDURE vbsRegister
@child1NAME varchar(2000),
@child1age tinyint,
@child1gradecompleted tinyint,
@child1birthdate varchar(50),
@child1tshirtsize varchar(5),
@child2NAME varchar(2000),
@child2age tinyint,
@child2gradecompleted tinyint,
@child2birthdate varchar(50),
@child2tshirtsize varchar(5),
@child3NAME varchar(2000),
@child3age tinyint,
@child3gradecompleted tinyint,
@child3birthdate varchar(50),
@child3tshirtsize varchar(5),
@address varchar(2000),
@citystatezip varchar(2000),
@parentguardian varchar(2000),
@phonehome varchar(30),
@phonework varchar(30),
@emercontact varchar(2000),
@emerphone varchar(30),
@invitedby varchar(2000),
@regattendrpc bit,
@regattendchurch bit
AS
INSERT INTO VBS_REGISTRATION
(
	child1NAME,
	child1age,
	child1gradecompleted,
	child1birthdate,
	child1tshirtsize,
	child2NAME,
	child2age,
	child2gradecompleted,
	child2birthdate,
	child2tshirtsize,
	child3NAME,
	child3age,
	child3gradecompleted,
	child3birthdate,
	child3tshirtsize,
	address,
	citystatezip,
	parentguardian,
	phonehome,
	phonework,
	emercontact,
	emerphone,
	invitedby,
	regattendrpc,
	regattendchurch,
	registerdate
)
VALUES
(
	@child1NAME,
	@child1age,
	@child1gradecompleted,
	@child1birthdate,
	@child1tshirtsize,
	@child2NAME,
	@child2age,
	@child2gradecompleted,
	@child2birthdate,
	@child2tshirtsize,
	@child3NAME,
	@child3age,
	@child3gradecompleted,
	@child3birthdate,
	@child3tshirtsize,
	@address,
	@citystatezip,
	@parentguardian,
	@phonehome,
	@phonework,
	@emercontact,
	@emerphone,
	@invitedby,
	@regattendrpc,
	@regattendchurch,
	GETDATE()
)